### PR TITLE
Restrict multiple logins by the same user

### LINKED ISSUE #25: Same user logged in twice should be disallowed.

### PR DESCRIPTION
**Pull request by TyrenDe**
This resolves #25. It also reduced traffic used by sleeping clients.

### CODE REVIEW

**Comment by adamk33n3r** [comment]
What's your reasoning for not using the auth for restricting login?

**Comment by TyrenDe** [comment]
I'm not sure I understand. The websocket client tries to login to the websocket (node.js) server. It replies with yes/no. I didn't think there was another way... is there?

**Comment by adamk33n3r** [comment]
Well right here https://github.com/TyrenDe/spacial_conquest/blob/tyren_dev/client/app/routes/home/home.controller.ts#L58. This function is called when the auth succeeds. The call is to here https://github.com/TyrenDe/spacial_conquest/blob/master/server/api/user/user.controller.ts#L32. Now currently there is no "session" stuff. But I'm planning to add that.

So right now the way you did it is the only way until i implement sessions.

**Comment by TyrenDe** [comment]
Awesome. So that! Yes, I'd love to have all of the auth in the same place. :) But for now, this will work.

**Comment by adamk33n3r** [comment]
Note that I actually didn't finish reviewing this

**Pull request merged**
